### ISSUE TITLE
Fjern tjenesten og publiser turtle-filer direkte fra repoet

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataservice-publisher#132]
Denne tjenesten baserer seg på en [fuseki-løsning](https://github.com/Informasjonsforvaltning/dataservice-publisher-sparql-service) som bruker [alt for mye ressurser](https://github.com/Informasjonsforvaltning/dataservice-publisher-sparql-service/issues/45) og er knotete å oppdatere.

Ved å gå over til samme måte som [model-publisher](https://github.com/Informasjonsforvaltning/model-publisher) fungerer på så vil filene være enklere å oppdatere og vi kan stenge ned ressurskrevende ressurser i kubernetes.

1. Legg til en kopi av denne katalogen i repoet: https://dataservice-publisher.digdir.no/catalogs/2, det er den eneste katalogen som i dag høstes herfra til prod.
2. Vurder om noen av test-katalogene som høstes i staging og demo også skal legges til
3. Endre høsteendepunktene til å peke på disse filene i admin.fellesdatakatalog.digdir.no
4. Steng ned dataservice-publisher i kubernetes
5. Steng ned dataservice-publisher-sparql-service og arkiver tilhørende [repo](https://github.com/Informasjonsforvaltning/dataservice-publisher-sparql-service)

**Comment by KurtStian** [comment]
Siden vi allerede har begynt å bruke registreringsløsningen for API og denne løsningen gjør det enklere å oppdatere beskrivelsene og mer synlig for resten av Digdir, foreslår jeg at vi flytter API-beskrivelsene som ligger på denne tjenesten til registreringsløsningen.

**Comment by NilsOveTen** [comment]
> Siden vi allerede har begynt å bruke registreringsløsningen for API og denne løsningen gjør det enklere å oppdatere beskrivelsene og mer synlig for resten av Digdir, foreslår jeg at vi flytter API-beskrivelsene som ligger på denne tjenesten til registreringsløsningen.

Må vi beholde fdk-metadata eller er det ok å bare fjerne disse og la de nye beskrivelsene fra registreringsløsningen få ny fdk-id osv?

**Comment by KurtStian** [comment]
Det er ikke ideelt at API-beskrivelsene får nye URI-er og FDK-id-er, men jeg tror det er lite sannsynlig at noen lenker til disse beskrivelsene. Beskrivelsene vil få en ny publiseringsdato, men tenker at dette ikke er så farlig. De fleste vil være mer interessert når beskrivelsen siste ble oppdatert.

Enig? @KjerstiSteien

**Comment by NilsOveTen** [comment]
Pratet med @KurtStian:

Vi starter med å flytte katalogene som nå er lagret på denne tjenesten ut som turtle-filer her i repoet, da kan vi stenge ned disse to tjenestene som skaper mye uro og bruker mange ressurser i GCP.

Å flytte datatjeneste over til registrering og medfølgende ETL tar vi som del 2 i et annet issue

**Comment by NilsOveTen** [comment]
Alt har blitt flytta over til registrering, lukker denne og arkiverer repoet
