### ISSUE TITLE
Support context when serving json-ld

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataservice-publisher#2]
cf https://github.com/RDFLib/rdflib-jsonld

**Comment by KjerstiSteien** [comment]
@KurtStian, @NilsOveTen, @terjesyl: Skjønner dere hva denne saken handler om, og er dette noe vi skal gjøre noe med? (var det denne tjenesten du nettopp hadde skrudd av, Nils Ove?

**Comment by NilsOveTen** [comment]
@KjerstiSteien Det går ut på fullstendig støtte av JSON-LD. Men du kan lukke det, ikke relevant.

https://github.com/Informasjonsforvaltning/dataservice-publisher/issues/132
☝️ Det er det eneste som kommer til å være relevant, lukker forhåpentligvis det i morgen, og da kan vi arkivere dette repoet

**Comment by valosnah** [comment]
Repo arkiveres, lukker
