### ISSUE TITLE
Ta vekk EndepunktsURL fra staging og demo i datatjenesten

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-publisher#26]
https://dataservice-publisher.digdir.no/catalogs/2
åpner du denne, finner du mange staging og demo url'er.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/60ce89c0-a748-4c04-afdd-4d9578d884db)

**Comment by NilsOveTen** [comment]
Er dette fortsatt et issue? Var kanskje bare jeg som glemte å lukke?

**Comment by NilsOveTen** [comment]
Flyttet enkelt og greit til test, @shenluna kan du ta en sjekk om vi har klart å fjerne alt av test/demo versjoner av fdk-api?

**Comment by shenluna** [comment]
Verifisert at endepunkter fra stag og demo ikke lenger vises.
