### ISSUE TITLE
Informasjonsmodeller - lenke for "i samsvar med" (dct:conformsTo) virker ikke

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/dataservice-publisher#31]
Gjelder egenskapen "i samsvar med" (dct:conformsTo) og modeller høstet fra Open API specification. I tillegg vises Versjon uten at den har noen verdi. Hvis det ikke er definert noe versjonsnummer for dct:Standard-klassen", som er range for dct:conformsTo, skal ikke versjonsfeltet vises. 
![image](https://user-images.githubusercontent.com/17720749/123618895-e9df5e00-d808-11eb-9c28-6d12ebdef838.png)

Gjelder modell: https://data.norge.no/informationmodels/14a8758e-d467-3dbf-8a90-64b6914cc45f

**Comment by matsjs** [comment]
ConformsTo kan peke mot https://bitsnorge.github.io/dsop-documentation/dsop_kontroll_api_specification.html

**Comment by stigbd** [comment]
Evt denne som peiker direkte på spekken, versjon 1
https://bitsnorge.github.io/dsop-accounts-api/

**Comment by stigbd** [comment]
Utfordring: Det er ein del "forretningslogikk" knytta til verdien av lenka i conformsTo (https://data.norge.no/specification/kontoopplysninger). Og denne logikken er ein premiss for at [DSOP kontrollinformasjon](https://www.bits.no/project/kontrollinformasjon/) skal fungere. Derfor er det litt tricky å endre på dette.

Alternative forslag:

1. La det vere som det er. (Lenka er død.)
2. Opprette redirect som følger: https://data.norge.no/specification/kontoopplysninger -> https://bitsnorge.github.io/dsop-accounts-api/

Kva seier du, @ToHelland ?

**Comment by ToHelland** [comment]
@stigbd 1. Lenka kan ikke være død, da tjener den ingen hensikt og bedre å ikke ha noe verdi conformsTo. 2. Ja, bedre løsning.

**Comment by stigbd** [comment]
Opprinneleg forslag står: Vi endrer conformsTO-lenka til å peike på bits

Plan:

1. - Vi må endre måten vi håndterer `serviceType` i fdk-portal og reference-data. (Lenke må vere key, navn på standard er value.) Ansvar: TBD
2. - Vi må endre lenka vi tester på i fdk-api-endpoints til å bruke bits-lenka. Ansvar: @NilsOveTen 
3. - Vi endrer lenka i dataservice-publisher Ansvar: @stigbd

**Comment by stigbd** [comment]
Dette er no fiksa. 
@shenluna : Gjerne verifiser før du lukker.

**Comment by shenluna** [comment]
Testet OK.
Se https://data.norge.no/informationmodels/164176b5-abb2-37e2-b11e-182e28d8131a
