### ISSUE TITLE
Oppgradering av pywin32

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/dataservice-publisher#38]
1 pywin32 vulnerability found in poetry.lock

Remediation

Upgrade pywin32 to version 301 or later.

**Comment by stigbd** [comment]
Eg greier ikkje finne ut av denne. Uklart for meg kva for pakke som har avhengigheter til pywin32. Må bruke litt meir tid.

**Comment by valosnah** [comment]
Ifølge Nils Ove er dette en test-dependency som ikke ender opp i det ferdige bygget. Ber dependabot om å ignorere, og lukker denne
