### ISSUE TITLE
Legg til format og/eller mediatype

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataservice-publisher#5]
Hent disse ut av openAPI-spec og legg på dataservice som https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_media_type, sjølv om dette ikkje er i tråd med dcat 2.

**Comment by lillelars** [comment]
@stigbd hva er egentlig denne tasken? Er det samme som Alex har gjort - eventuelt kan vil lukke denne?
Alex har lagt inn alle mediatypes i reference data.

**Comment by stigbd** [comment]
Denne saka dreier seg om å legge til format (dvs mediatypes) i vår dataservice-publisher tjeneste.

Eg jobbar med å lage ein måte å hente denne ut av ein openAPI-spesifikasjon og eksponere den ut av vår dataservice-publisher ihht DCAT-AP-NO v2.

**Comment by lillelars** [comment]
er denne relevant lenger? Har vi ikke dette? @stigbd

**Comment by stigbd** [comment]
Lukker denne da denne funksjonen er støtta av https://pypi.org/project/oastodcat/
